import Container from "@/components/Layout/Container";
import Footer from "@/components/Layout/Footer";
import Header from "@/components/Layout/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="emerald">
      <body className="antialiased h-screen grid grid-rows-[auto_1fr_auto] gap-y-5">
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
