import AuthLayout from "@/components/Layout/AuthLayout";
import Footer from "@/components/Layout/Footer";
import Header from "@/components/Layout/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="skillsync-tech"
      className={`${inter.className} ${inter.variable}`}
    >
      <body className="antialiased grid grid-rows-[auto_1fr_auto] gap-y-5">
        <AuthLayout>
          <Header />
          {children}
          <Footer />
        </AuthLayout>
      </body>
    </html>
  );
}
