import Container from "@/components/Layout/Container";
import { Inter } from "next/font/google";
import MinimalHeader from "@/components/Layout/MinimalHeader";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="skillsync-tech"
      className={`${inter.className} ${inter.variable}`}
    >
      <body className="antialiased h-screen grid grid-rows-[auto_1fr_auto] gap-y-5">
        <MinimalHeader />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
